"""Gemini AI client for generating content using Google's Gemini API."""

import os
import json
from typing import Optional, Dict, Any
import httpx
from pydantic import BaseModel, Field


class GeminiRequest(BaseModel):
    """Request model for Gemini API calls."""
    prompt: str = Field(..., description="The prompt to send to Gemini")
    max_tokens: Optional[int] = Field(default=4000, description="Maximum number of tokens to generate")
    temperature: Optional[float] = Field(default=0.7, description="Sampling temperature (0.0 to 1.0)")


class GeminiResponse(BaseModel):
    """Response model from Gemini API."""
    content: str = Field(..., description="Generated text content")


class GeminiClient:
    """Client for interacting with Google's Gemini API."""

    def __init__(self, api_key: str, model_name: str = "gemini-2.0-flash-exp"):
        """
        Initialize Gemini client.

        Args:
            api_key: Google AI API key
            model_name: Gemini model to use (default: gemini-2.0-flash-exp)
        """
        if not api_key:
            raise ValueError("Gemini API key is required")

        self.api_key = api_key
        self.model_name = model_name
        self.base_url = "https://generativelanguage.googleapis.com/v1beta/models"

    async def generate_content(self, request: GeminiRequest) -> GeminiResponse:
        """
        Generate content using Gemini API.

        Args:
            request: GeminiRequest with prompt and configuration

        Returns:
            GeminiResponse with generated content and usage stats

        Raises:
            Exception: If API call fails
        """
        try:
            url = f"{self.base_url}/{self.model_name}:generateContent?key={self.api_key}"

            headers = {
                "Content-Type": "application/json",
            }

            data = {
                "contents": [
                    {
                        "parts": [
                            {
                                "text": request.prompt
                            }
                        ]
                    }
                ],
                "generationConfig": {
                    "maxOutputTokens": request.max_tokens or 4000,
                    "temperature": request.temperature or 0.7,
                }
            }

            async with httpx.AsyncClient(timeout=60.0) as client:
                response = await client.post(url, headers=headers, json=data)

                if not response.is_success:
                    error_text = response.text
                    raise Exception(f"HTTP {response.status_code}: {error_text}")

                response_data = response.json()

                # Extract the generated text from Gemini's response format
                generated_text = ""
                if "candidates" in response_data and len(response_data["candidates"]) > 0:
                    candidate = response_data["candidates"][0]
                    if "content" in candidate and "parts" in candidate["content"]:
                        parts = candidate["content"]["parts"]
                        if len(parts) > 0 and "text" in parts[0]:
                            generated_text = parts[0]["text"]

                if not generated_text:
                    raise Exception("No content generated by Gemini")

                return GeminiResponse(content=generated_text)

        except Exception as error:
            print(f"Gemini API Error: {error}")
            raise Exception(f"Gemini API call failed: {str(error)}")
